### ISSUE TITLE
Geospatial functions not found after recent updates

### ISSUE THREAD

**Issue by SSoetaert** [iulian0512/android_spatialite#2]
Hi, 

Since the latest new version of the sqlite package, the geospatial functions do not work anymore. 
I saw in the read me of the darwin folder that the FMDB package is not added anymore as a dependency.
Did I forgot to do something?

Kind Regards,
Sander

**Comment by iulian0512** [comment]
provide a complete minimal example

**Comment by iulian0512** [comment]
@SSoetaert  i have merged with the latest sqflite see https://github.com/iulian0512/sqflite master branch

you will also need these overrides in pubspec.yaml
```
  sqflite:
    git:
      url: https://github.com/iulian0512/sqflite
      path: sqflite
      ref: b433114c1f4481bd1aa72c56a1e29953b1533bb5

  sqflite_common_ffi:
    git:
      url: https://github.com/iulian0512/sqflite
      path: sqflite_common_ffi
      ref: b433114c1f4481bd1aa72c56a1e29953b1533bb5

  sqflite_darwin:
    git:
      url: https://github.com/iulian0512/sqflite
      path: sqflite_darwin
      ref: b433114c1f4481bd1aa72c56a1e29953b1533bb5

  sqflite_android:
    git:
      url: https://github.com/iulian0512/sqflite
      path: sqflite_android
      ref: b433114c1f4481bd1aa72c56a1e29953b1533bb5
  
```
